chore: 修改Cypress退出代码判断 (#92)
* chore: 调整Cypress退出代码检查

* chore: 处理 Cypress 错误退出的判断，增加视频录制

* chore: update cypress-io/github-action to v6

* chore: 增加等待时间

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -1,4 +1,5 @@
 name: e2e-tests
+
 on:
   push:
     branches:
@@ -43,12 +44,15 @@ jobs:
         run: pnpm exec cypress info
 
       - name: Run Cypress tests
-        uses: cypress-io/github-action@v5
+        id: run-cypress
+        uses: cypress-io/github-action@v6
         env:
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
         with:
           start: npm run dev
           wait-on: http://localhost:3000
+          wait-on-timeout: 120
+          # 让测试继续运行，不影响上传步骤
         continue-on-error: true
 
       - name: Upload screenshots
@@ -57,5 +61,19 @@ jobs:
           name: screenshots-headless-chrome
           path: ./cypress/screenshots
 
-      - name: Check screenshot dimensions
-        run: npx image-size cypress/screenshots/**/*.png
+      - name: Upload Cypress Videos
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: cypress-videos
+          path: ./cypress/videos
+
+      - name: Check Cypress exit code
+        if: always()
+        run: |
+          if [ "${{ steps.run-cypress.outcome }}" != "success" ]; then
+            echo "❌ Cypress tests failed"
+            exit 1
+          else
+            echo "✅ Cypress tests passed"
+          fi
